### PR TITLE
feature/implement-page-on-query-model

### PR DESCRIPTION
**Pull request by eisenbergrobin**
Implements a `page` interface on `Query`.

### CODE REVIEW

**Comment by zallek** [comment]
you would need size also isn't ?

**Comment by eisenbergrobin** [comment]
I don't. Others might, but all I need is paging. 
If I'm not mistaken the API defaults to size=100 if no size is given. Can you confirm ?

Should I still implement a pageSize ?

**Comment by zallek** [comment]
yeh and you shoul dbe able to go up to 1k

**Comment by eisenbergrobin** [comment]
Ready for review. I did not add pageSize limits because @pleasedontbelong told me that different endpoints have different limits.

**Comment by eisenbergrobin** [comment]
@zallek If you review this OK, could you also merge and run the release script? 
For one, I don't have npm access, and also it's not working on Windows.

**Pull request merged**
